### ISSUE TITLE
No sort for upper and lower case letters

### ISSUE THREAD

**Issue by hanyska** [mdmoin7/angular-sort-orderby-pipe#1]
STACKBLITZ: https://stackblitz.com/edit/angular-sort-orderby-pipe-1ydfng?file=src%2Fapp%2Fapp.component.ts

No sort for upper and lower case letters

**Comment by mdmoin7** [comment]
as we are aware that sorting happens based on ascii values not on any other context, if you would have need to sort, you can still achieve that logically by converting all the text into one case & than do the comparison.
You can try this
https://stackblitz.com/edit/angular-sort-insensitive-pipe
